/* Generated By:JavaCC: Do not edit this line. ConfigsReaderConstants.java */
package edu.casetools.mreasoner.configurations.reader;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConfigsReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int QUOTE = 9;
  /** RegularExpression Id. */
  int ENDQUOTE = 11;
  /** RegularExpression Id. */
  int CHAR = 12;
  /** RegularExpression Id. */
  int CNTRL_ESC = 13;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 14;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 15;
  /** RegularExpression Id. */
  int POINT = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int TWO_POINT = 18;
  /** RegularExpression Id. */
  int SLASH = 19;
  /** RegularExpression Id. */
  int COUNTER_SLASH = 20;
  /** RegularExpression Id. */
  int LOWER = 21;
  /** RegularExpression Id. */
  int HIGHER = 22;
  /** RegularExpression Id. */
  int HYPHEN = 23;
  /** RegularExpression Id. */
  int UNDERSCORE = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int ALPHABET = 26;
  /** RegularExpression Id. */
  int CAPSALPHABET = 27;
  /** RegularExpression Id. */
  int STRING = 28;
  /** RegularExpression Id. */
  int EXECUTION_MODE = 29;
  /** RegularExpression Id. */
  int EXECUTION_MODE_END = 30;
  /** RegularExpression Id. */
  int STRATIFICATION = 31;
  /** RegularExpression Id. */
  int STRATIFICATION_END = 32;
  /** RegularExpression Id. */
  int USE_FIXED_ITERATION_TIME = 33;
  /** RegularExpression Id. */
  int USE_FIXED_ITERATION_TIME_END = 34;
  /** RegularExpression Id. */
  int FIXED_ITERATION_TIME = 35;
  /** RegularExpression Id. */
  int FIXED_ITERATION_TIME_END = 36;
  /** RegularExpression Id. */
  int USE_MAX_EXECUTION_TIME = 37;
  /** RegularExpression Id. */
  int USE_MAX_EXECUTION_TIME_END = 38;
  /** RegularExpression Id. */
  int EXECUTION_TIME = 39;
  /** RegularExpression Id. */
  int EXECUTION_TIME_END = 40;
  /** RegularExpression Id. */
  int RELATIVE_TIME_IS_ITERATION = 41;
  /** RegularExpression Id. */
  int RELATIVE_TIME_IS_ITERATION_END = 42;
  /** RegularExpression Id. */
  int RELATIVE_VALUE = 43;
  /** RegularExpression Id. */
  int RELATIVE_VALUE_END = 44;
  /** RegularExpression Id. */
  int ABSOLUTE_TIME_IS_ITERATION = 45;
  /** RegularExpression Id. */
  int ABSOLUTE_TIME_IS_ITERATION_END = 46;
  /** RegularExpression Id. */
  int DATABASE_TYPE = 47;
  /** RegularExpression Id. */
  int DATABASE_TYPE_END = 48;
  /** RegularExpression Id. */
  int DATABASE_DRIVER = 49;
  /** RegularExpression Id. */
  int DATABASE_DRIVER_END = 50;
  /** RegularExpression Id. */
  int DATABASE_TABLE_GENERIC = 51;
  /** RegularExpression Id. */
  int DATABASE_TABLE_GENERIC_END = 52;
  /** RegularExpression Id. */
  int DATABASE_IP = 53;
  /** RegularExpression Id. */
  int DATABASE_IP_END = 54;
  /** RegularExpression Id. */
  int DATABASE_PORT = 55;
  /** RegularExpression Id. */
  int DATABASE_PORT_END = 56;
  /** RegularExpression Id. */
  int DATABASE_USER = 57;
  /** RegularExpression Id. */
  int DATABASE_USER_END = 58;
  /** RegularExpression Id. */
  int DATABASE_PASSWORD = 59;
  /** RegularExpression Id. */
  int DATABASE_PASSWORD_END = 60;
  /** RegularExpression Id. */
  int SYSTEM_SPECIFICATION_FILE_PATH = 61;
  /** RegularExpression Id. */
  int SYSTEM_SPECIFICATION_FILE_PATH_END = 62;
  /** RegularExpression Id. */
  int DATABASE_NAME = 63;
  /** RegularExpression Id. */
  int DATABASE_NAME_END = 64;
  /** RegularExpression Id. */
  int JARS_CONFIGS = 65;
  /** RegularExpression Id. */
  int JARS_CONFIGS_END = 66;
  /** RegularExpression Id. */
  int LFPUBS_OUTPUT_FILE_PATH = 67;
  /** RegularExpression Id. */
  int LFPUBS_OUTPUT_FILE_PATH_END = 68;
  /** RegularExpression Id. */
  int SESSION_FILE_PATH = 69;
  /** RegularExpression Id. */
  int SESSION_FILE_PATH_END = 70;
  /** RegularExpression Id. */
  int RESULTS_FILE_PATH = 71;
  /** RegularExpression Id. */
  int RESULTS_FILE_PATH_END = 72;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INSIDE_COMMENT = 1;
  /** Lexical state. */
  int STRING_STATE = 2;
  /** Lexical state. */
  int ESC_STATE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"\\\"\"",
    "\"\\\\\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "<CNTRL_ESC>",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\"/\"",
    "\"\\\\\"",
    "\"<\"",
    "\">\"",
    "\"-\"",
    "<UNDERSCORE>",
    "<DIGIT>",
    "<ALPHABET>",
    "<CAPSALPHABET>",
    "<STRING>",
    "\"<EXECUTION_MODE>\"",
    "\"</EXECUTION_MODE>\"",
    "\"<USE_STRATIFICATION>\"",
    "\"</USE_STRATIFICATION>\"",
    "\"<USE_FIXED_ITERATION_TIME>\"",
    "\"</USE_FIXED_ITERATION_TIME>\"",
    "\"<FIXED_ITERATION_TIME>\"",
    "\"</FIXED_ITERATION_TIME>\"",
    "\"<USE_MAX_EXECUTION_TIME>\"",
    "\"</USE_MAX_EXECUTION_TIME>\"",
    "\"<EXECUTION_TIME>\"",
    "\"</EXECUTION_TIME>\"",
    "\"<RELATIVE_TIME_IS_ITERATION>\"",
    "\"</RELATIVE_TIME_IS_ITERATION>\"",
    "\"<RELATIVE_TIME_VALUE>\"",
    "\"</RELATIVE_TIME_VALUE>\"",
    "\"<ABSOLUTE_TIME_IS_ITERATION>\"",
    "\"</ABSOLUTE_TIME_IS_ITERATION>\"",
    "\"<DATABASE_TYPE>\"",
    "\"</DATABASE_TYPE>\"",
    "\"<DATABASE_DRIVER>\"",
    "\"</DATABASE_DRIVER>\"",
    "\"<DATABASE_TABLE_GENERIC>\"",
    "\"</DATABASE_TABLE_GENERIC>\"",
    "\"<DATABASE_IP>\"",
    "\"</DATABASE_IP>\"",
    "\"<DATABASE_PORT>\"",
    "\"</DATABASE_PORT>\"",
    "\"<DATABASE_USER>\"",
    "\"</DATABASE_USER>\"",
    "\"<DATABASE_PASSWORD>\"",
    "\"</DATABASE_PASSWORD>\"",
    "\"<SYSTEM_SPECIFICATION_FILE_PATH>\"",
    "\"</SYSTEM_SPECIFICATION_FILE_PATH>\"",
    "\"<DATABASE_NAME>\"",
    "\"</DATABASE_NAME>\"",
    "\"<EXTERNAL_JARS>\"",
    "\"</EXTERNAL_JARS>\"",
    "\"<LFPUBS_OUTPUT_FILE_PATH>\"",
    "\"</LFPUBS_OUTPUT_FILE_PATH>\"",
    "\"<SESSION_FILE_PATH>\"",
    "\"</SESSION_FILE_PATH>\"",
    "\"<RESULTS_FILE_PATH>\"",
    "\"</RESULTS_FILE_PATH>\"",
  };

}
